[package]
name = "iota-network-stack"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "IOTA's network tooling"

[dependencies]
anemo = { workspace = true, optional = true }
bcs = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
eyre.workspace = true
futures = { workspace = true, optional = true }
http = { workspace = true, optional = true }
multiaddr = "0.17.0"
pin-project-lite = { version = "0.2.13", optional = true }
serde.workspace = true
snap = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync", "rt", "macros"], optional = true }
tokio-stream = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
tonic-health = { workspace = true, optional = true }
tower = { workspace = true, optional = true }
tower-http = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[features]
default = ["risc0-hack"]
risc0-hack = [
  "dep:anemo",
  "dep:bcs",
  "dep:bytes",
  "dep:futures",
  "dep:http",
  "dep:pin-project-lite",
  "dep:snap",
  "dep:tokio",
  "dep:tokio-stream",
  "dep:tonic",
  "dep:tonic-health",
  "dep:tower",
  "dep:tower-http",
  "dep:tracing",
]
