services:
  tempo:
    networks:
        - monitoring

  prometheus:
    networks:
      - monitoring

  grafana:
    networks:
      - monitoring

  node-exporter:
    networks:
      - monitoring

networks:
  monitoring:
    external: true