services:
  tempo:
    networks:
        - iota-network

  prometheus:
    networks:
      - iota-network

  grafana:
    networks:
      - iota-network

  node-exporter:
    networks:
      - iota-network

networks:
  iota-network:
    external:
        name: iota-network-node