[package]
name = "move-model"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# internal dependencies
move-binary-format.workspace = true
move-bytecode-source-map = { workspace = true, default-features = true }
move-command-line-common = { workspace = true, default-features = true }
move-compiler = { workspace = true, default-features = true }
move-core-types.workspace = true
move-disassembler = { workspace = true, default-features = true }
move-ir-types = { workspace = true, default-features = true }
move-symbol-pool.workspace = true

# external dependencies
anyhow.workspace = true
codespan.workspace = true
codespan-reporting.workspace = true
itertools.workspace = true
log.workspace = true
num.workspace = true
once_cell.workspace = true
regex.workspace = true
serde.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
move-prover-test-utils.workspace = true

[[test]]
name = "testsuite"
harness = false

[features]
default = ["risc0-hack"]
risc0-hack = [
  "move-bytecode-source-map/risc0-hack",
  "move-command-line-common/risc0-hack",
  "move-compiler/risc0-hack",
  "move-disassembler/risc0-hack",
  "move-ir-types/risc0-hack",
]
