[package]
name = "iota-execution"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Multiplexer to choose between multiple versions of iota and move execution crates."

[dependencies]
iota-adapter-latest = { path = "latest/iota-adapter" }
# iota-adapter-$CUT = { path = "$CUT/iota-adapter" }
iota-move-natives-latest = { path = "latest/iota-move-natives" }
iota-protocol-config.workspace = true
iota-types.workspace = true
# iota-move-natives-$CUT = { path = "$CUT/iota-move-natives" }
iota-verifier-latest = { path = "latest/iota-verifier" }
iota0-core = { path = "../../../iota0/core", features = ["iota-executor", "risc0", "prove"], optional = true }
move-binary-format.workspace = true
# iota-verifier-$CUT = { path = "$CUT/iota-verifier" }
move-bytecode-verifier-latest = { path = "../external-crates/move/crates/move-bytecode-verifier", package = "move-bytecode-verifier" }
move-bytecode-verifier-meter.workspace = true
move-vm-config.workspace = true
# move-bytecode-verifier-$CUT = { path = "../external-crates/move/move-execution/$CUT/crates/move-bytecode-verifier" }
move-vm-runtime-latest = { path = "../external-crates/move/crates/move-vm-runtime", package = "move-vm-runtime" }
# move-vm-runtime-$CUT = { path = "../external-crates/move/move-execution/$CUT/crates/move-vm-runtime" }

[dev-dependencies]
cargo_metadata = "0.15"
petgraph = "0.6"

[features]
default = [
  "risc0-hack",
  # TODO: enable "risc0-hack-iota0" by default
]
risc0-hack = [
  "iota-adapter-latest/risc0-hack",
  "iota-move-natives-latest/risc0-hack",
  "iota-protocol-config/risc0-hack",
  "iota-types/risc0-hack",
]
risc0-hack-iota0 = [
  "dep:iota0-core",
  "iota-protocol-config/risc0-hack-iota0",
]

gas-profiler = [
  "iota-adapter-latest/gas-profiler",
  "move-vm-config/gas-profiler",
  "move-vm-runtime-latest/gas-profiler",
  # "iota-adapter-$CUT/gas-profiler",
  # "move-vm-runtime-$CUT/gas-profiler",
]
