[package]
name = "move-compiler"
version = "0.0.1"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "The definition of the Move source language, and its compiler"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, optional = true }
codespan-reporting.workspace = true
dunce.workspace = true
hex.workspace = true
lsp-types.workspace = true
once_cell.workspace = true
petgraph.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
similar = { workspace = true, optional = true }
stacker = { workspace = true, optional = true }
vfs = { workspace = true, optional = true }

bcs.workspace = true

move-binary-format.workspace = true
move-borrow-graph.workspace = true
move-bytecode-source-map.workspace = true
move-bytecode-verifier.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-ir-to-bytecode.workspace = true
move-ir-types.workspace = true
move-proc-macros.workspace = true
move-symbol-pool.workspace = true

[dev-dependencies]
datatest-stable.workspace = true
move-stdlib.workspace = true

[features]
default = ["risc0-hack"]
risc0-hack = [
  "move-bytecode-source-map/risc0-hack",
  "move-command-line-common/risc0-hack",
  "move-ir-to-bytecode/risc0-hack",
  "move-ir-types/risc0-hack",
  "dep:clap",
  "dep:similar",
  "dep:stacker",
  "dep:vfs",
]

[[test]]
name = "move_check_testsuite"
harness = false
